language: ruby
dist: trusty
deploy:
  provider: rubygems
  gem: c100bit-nmax
  on:
    repo: c100bit/nmax
  api_key:
    secure: ezF5RRcpYFuDrbU0Kf3jSokQJ4rQ5dL4le92u7x0LeX+fObM+PkR4qIkm2zPwfo2xeRQEGcWZVvkhagFCngI7zOHh9zqFKJLszxBaVIqn50HfMLUHKUBdj4/FK3lJjqd7BWMui85JjPktdyUQJkDwmM30IWQ3cTjBOgTWo3LRuykmEbWGN56Wdg8nJ/KSO9XrvsqvKpL2n4ThnwEq+V+41NzQMs0YtBnJKUbal1oPpb2AzRNSaD7yhEgMtcrDCH+YsR7y/qSFR01bJBzhCKqUna3yhHb+EPgo+rUTkGvEwDdREnq2ZNuvIlb3RJwatRUbqeOWdZHS1w8VZfsmVPUC1lS6Y5GC7qay+CGM9Z0hDUNflfRfDmLFP23fLc461e4dUkY65Mpr+xwnYidP434ouYcw5oE/hlThIJcX1PVDzWFG3L2B8Fm49Soa6yieic79vKvrGCoLmktYRmwCGm9bx9S70iwWAynjcidKXvh0JA04T0eHFe6Tgv88LEjlzbz3w5El8OHExNWQGTZZ0uWY0B1QCKU1VsOQ/qZyabeaxbIG6MK918alEaL7d2z6vjNG9ekDrv5mqelG6cXQJeEafcSgUtUCvO9NdegqML/BfhFsF9zuiHapcSGldhRXqYZYvWuNdFgCnv3S+ljlG7eknEzKzuqrDCDEVfdcjOxf2c=
